### ISSUE TITLE
KDL TODO list

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kdl-server#227]
### General
- [x] Update buttons (most of them now use Capitalized text instead of UPPERCASED.

### Settings
- [x] Settings panel is positioned over all elements, it should allow seeing the user menu.
- [x] Open Member Details when clicking on a member row, not just the Open button (which is too small)
- [x] Add bulk actions to members (allowing multiple removals and multiple member level updates).

### User Tools
- [x] Open VsCode/Jupyter directly on the project directory so the user does not have to navigate to them.
- [x] Stop tools stopped working.
- [x] Add `top: 0;` to iframes container so they do not generate scrolling, 

### Knowledge Galaxy
- [x] Add relevance to topics on topic list.
- [x] Add order on topic boxes so it is more evident they are sorted.
- [x] Change selected paper accent color and add an animation to it.
- [x] Add Star/Unstar actions.
- [x] Update score axis labels (more offset, add a small background and position over resources).
- [ ] Make topic boxes clickable (this action will filter resources on resource list).
- [x] Add KG loading animation.
- [x] Resizing makes an ugly effect, add a short debounce
- [x] Recalibrate scrolling. 
- [x] Review panel lists space breaks (do not break words, break topic tags)
- [x] Review z-index on kg and locate tooltip over section boxes.
- [x] Add scroll to resource details abstract (panel).
- [x] Review paper details: show more information and links when resource is a PaperWithCode paper.
- [x] Update KG Resource Code layout

### Discussion
- [ ] I would like to see a Topic not included in the Top 9.
- [ ] What happens when a paper contains several topics (in a lot of cases more than one topic has 100% of score).
- [x] When hidding a topic, I would like to include those papers inside Others category.
