### ISSUE TITLE
Label ServiceAccount for users when they are created from the kdl app

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kdl-server#848]
As a KAI Lab Operator
I want Kubernetes ServiceAccounts labeled
In order to be able to filter or perform operations on filtered groups

** Tasks **

- [X] Generally upgrade Go to 1.18 to make use of workspaces
  - [x] repo-cloner (https://github.com/konstellation-io/kdl-server/pull/855) 
  - [x] cleaner (https://github.com/konstellation-io/kdl-server/pull/856)
  - [x] gitea-oauth2-setup (https://github.com/konstellation-io/kdl-server/pull/857)
  - [x] app (https://github.com/konstellation-io/kdl-server/pull/859)
- [x] Add labels when creating or synchronizing serviceaccounts 
  - [x] Add labels to configmap (https://github.com/konstellation-io/kdl-server/compare/feat/common-labels?expand=1)
  - [ ] (https://github.com/konstellation-io/kdl-server/pull/859)

** Definition of Done **

- [ ] Deployed in production
