### ISSUE TITLE
Test restore KDL backup

### ISSUE THREAD

**Issue by aacecandev** [konstellation-io/kdl-server#861]
As a KAI Lab Operator
I want to test the restore process
To be confident that we can trust the Disaster Recovery in case of failure in Dell

** Tasks **

- [x] Fix the backup cronjob to exclude `/data/lost+found` (https://github.com/konstellation-io/kdl-server/pull/862) and create a fresh backup of INT
- [x] Replicate the microk8s environment (version + addons) in a separate machine
- [x] Fake cert-manager to achieve a fresh deployment of kdl
- [x] Fix the backup image/cronjob (https://github.com/konstellation-io/kdl-server/pull/863)

** Definition of Done **

- [x] Backup process has been performed successfully
- [x] Backup process is available as code
- [x] Backup process has been documented
- [x] Restore process has been performed successfully
- [x] Restore process has been documented
- [x] Restore process is available as code
